#shortcuts for Torch extensions

import Echo.Activation.Torch.weightedTanh as weightedTanh
from Echo.Activation.Torch.mish import mish
from Echo.Activation.Torch.silu import silu
from Echo.Activation.Torch.aria2 import aria2
from Echo.Activation.Torch.eswish import eswish
from Echo.Activation.Torch.swish import swish
from Echo.Activation.Torch.beta_mish import beta_mish
from Echo.Activation.Torch.elish import elish
from Echo.Activation.Torch.hard_elish import hard_elish
from Echo.Activation.Torch.mila import mila
from Echo.Activation.Torch.sine_relu import sine_relu
from Echo.Activation.Torch.fts import fts
from Echo.Activation.Torch.sqnl import sqnl
from Echo.Activation.Torch.isru import isru
from Echo.Activation.Torch.isrlu import isrlu
from Echo.Activation.Torch.bent_id import bent_id
from Echo.Activation.Torch.soft_clipping import soft_clipping
from Echo.Activation.Torch.apl import apl
from Echo.Activation.Torch.brelu import brelu
from Echo.Activation.Torch.maxout import maxout
from Echo.Activation.Torch.soft_exponential import soft_exponential
from Echo.Activation.Torch.srelu import srelu
import Echo.Activation.Torch.functional as Func
